name: Actions workflow


on: [push]


jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: | 
          pwd
          ls
      - name: simple JS Action
        id: Ansh
        uses: rajkumar25maurya/raj-js@a8956661d70509a8a7d8271a65c41f8327fec526
        with:
          who-to-greet: Raj
      - name: Lo Greetting time
        run: echo "${{ steps.Ansh.outputs.time }}"
