name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:  
    -   name: echo a string
        run: echo "Hello Shyam"
    
    -   name: echo multiline script
        run: |
          node -v
          npm -v
          uname -r 
    
    - name: Python command
      run: |
        import platform
        print(platform.processor())
      shell: python